name: ClimateEnv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.5.30=py36h06a4308_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.68.2=h36276a3_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py36h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.3.4=py36h06a4308_0
  - matplotlib-base=3.3.4=py36h62a2d02_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1l=h7f8727e_0
  - pcre=8.44=he6710b0_0
  - pillow=8.2.0=py36he98fc37_0
  - pip=21.1.1=py36h06a4308_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.13=hdb3f193_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py36h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=52.0.0=py36h06a4308_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py36h27cfd23_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - bootstrapped==0.0.2
    - click==8.0.1
    - importlib-metadata==4.6.3
    - pandas==1.1.5
    - pickle5==0.0.12
    - pytz==2021.1
    - seaborn==0.11.1
    - typing-extensions==3.10.0.0
    - zipp==3.5.0
prefix: /home/elena/anaconda3/envs/ClimateEnv
